/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    DispatchedRoutesTable: typeof import('./components/DispatchedRoutesTable.vue')['default']
    DriverAvailabilityDialog: typeof import('./components/DriverAvailabilityDialog.vue')['default']
    DriverAvailabilityEditDialog: typeof import('./components/DriverAvailabilityEditDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouteMissingAssignments: typeof import('./components/RouteMissingAssignments.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteStopCard: typeof import('./components/RouteStopCard.vue')['default']
    RouteStopNotesDialog: typeof import('./components/RouteStopNotesDialog.vue')['default']
  }
}
