/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/activity': RouteRecordInfo<'/admin/activity', '/admin/activity', Record<never, never>, Record<never, never>>,
    '/admin/geotab': RouteRecordInfo<'/admin/geotab', '/admin/geotab', Record<never, never>, Record<never, never>>,
    '/admin/history': RouteRecordInfo<'/admin/history', '/admin/history', Record<never, never>, Record<never, never>>,
    '/admin/import': RouteRecordInfo<'/admin/import', '/admin/import', Record<never, never>, Record<never, never>>,
    '/admin/logging': RouteRecordInfo<'/admin/logging', '/admin/logging', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/customers/': RouteRecordInfo<'/customers/', '/customers', Record<never, never>, Record<never, never>>,
    '/customers/[id]': RouteRecordInfo<'/customers/[id]', '/customers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dispatch/': RouteRecordInfo<'/dispatch/', '/dispatch', Record<never, never>, Record<never, never>>,
    '/dispatch/terminals/[id]': RouteRecordInfo<'/dispatch/terminals/[id]', '/dispatch/terminals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/drivers/': RouteRecordInfo<'/drivers/', '/drivers', Record<never, never>, Record<never, never>>,
    '/drivers/[id]': RouteRecordInfo<'/drivers/[id]', '/drivers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/fleet/': RouteRecordInfo<'/fleet/', '/fleet', Record<never, never>, Record<never, never>>,
    '/operations-hub': RouteRecordInfo<'/operations-hub', '/operations-hub', Record<never, never>, Record<never, never>>,
    '/planning/': RouteRecordInfo<'/planning/', '/planning', Record<never, never>, Record<never, never>>,
    '/planning/[id]': RouteRecordInfo<'/planning/[id]', '/planning/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/routes/': RouteRecordInfo<'/routes/', '/routes', Record<never, never>, Record<never, never>>,
    '/routes/[id]': RouteRecordInfo<'/routes/[id]', '/routes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/routes/[id]/planning': RouteRecordInfo<'/routes/[id]/planning', '/routes/:id/planning', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/terminals/': RouteRecordInfo<'/terminals/', '/terminals', Record<never, never>, Record<never, never>>,
    '/terminals/[id]': RouteRecordInfo<'/terminals/[id]', '/terminals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user-auth': RouteRecordInfo<'/user-auth', '/user-auth', Record<never, never>, Record<never, never>>,
    '/user-profile': RouteRecordInfo<'/user-profile', '/user-profile', Record<never, never>, Record<never, never>>,
  }
}
